/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpleadosRouteImport } from './routes/empleados'
import { Route as AsistenciaRouteImport } from './routes/asistencia'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadosRoute = EmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenciaRoute = AsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/empleados': typeof EmpleadosRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/empleados': typeof EmpleadosRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/empleados': typeof EmpleadosRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asistencia' | '/empleados' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asistencia' | '/empleados' | '/login'
  id: '__root__' | '/' | '/asistencia' | '/empleados' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenciaRoute: typeof AsistenciaRoute
  EmpleadosRoute: typeof EmpleadosRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleados': {
      id: '/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof EmpleadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistencia': {
      id: '/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenciaRoute: AsistenciaRoute,
  EmpleadosRoute: EmpleadosRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
